//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 12/2/2013 9:40:06 AM
namespace ClientApp.Formula1Service
{
    
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Formula1ServiceSample.Models", "ClientApp.Formula1Service");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("ClientApp.Formula1Service", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Formula1ServiceSample.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Racer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Racer> Racer
        {
            get
            {
                if ((this._Racer == null))
                {
                    this._Racer = base.CreateQuery<Racer>("Racer");
                }
                return this._Racer;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Racer> _Racer;
        /// <summary>
        /// There are no comments for RaceResult in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RaceResult> RaceResult
        {
            get
            {
                if ((this._RaceResult == null))
                {
                    this._RaceResult = base.CreateQuery<RaceResult>("RaceResult");
                }
                return this._RaceResult;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RaceResult> _RaceResult;
        /// <summary>
        /// There are no comments for Race in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Race> Race
        {
            get
            {
                if ((this._Race == null))
                {
                    this._Race = base.CreateQuery<Race>("Race");
                }
                return this._Race;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Race> _Race;
        /// <summary>
        /// There are no comments for Circuit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Circuit> Circuit
        {
            get
            {
                if ((this._Circuit == null))
                {
                    this._Circuit = base.CreateQuery<Circuit>("Circuit");
                }
                return this._Circuit;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Circuit> _Circuit;
        /// <summary>
        /// There are no comments for Racer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRacer(Racer racer)
        {
            base.AddObject("Racer", racer);
        }
        /// <summary>
        /// There are no comments for RaceResult in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRaceResult(RaceResult raceResult)
        {
            base.AddObject("RaceResult", raceResult);
        }
        /// <summary>
        /// There are no comments for Race in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRace(Race race)
        {
            base.AddObject("Race", race);
        }
        /// <summary>
        /// There are no comments for Circuit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCircuit(Circuit circuit)
        {
            base.AddObject("Circuit", circuit);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"Formula1ServiceSample.Models\" xmlns=\"http://schemas.microsoft.com/ado" +
                "/2009/11/edm\"><EntityType Name=\"Racer\"><Key><PropertyRef Name=\"Id\" /></Key><Prop" +
                "erty Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Firstname\" Ty" +
                "pe=\"Edm.String\" /><Property Name=\"Lastname\" Type=\"Edm.String\" /><Property Name=\"" +
                "Country\" Type=\"Edm.String\" /><Property Name=\"Starts\" Type=\"Edm.Int32\" /><Propert" +
                "y Name=\"Wins\" Type=\"Edm.Int32\" /><NavigationProperty Name=\"RaceResults\" Relation" +
                "ship=\"Formula1ServiceSample.Models.Formula1ServiceSample_Models_Racer_RaceResult" +
                "s_Formula1ServiceSample_Models_RaceResult_RaceResultsPartner\" ToRole=\"RaceResult" +
                "s\" FromRole=\"RaceResultsPartner\" /></EntityType><EntityType Name=\"RaceResult\"><K" +
                "ey><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=" +
                "\"false\" /><Property Name=\"RaceId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property " +
                "Name=\"Position\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Grid\" Type=\"" +
                "Edm.Int32\" /><Property Name=\"Points\" Type=\"Edm.Decimal\" /><Property Name=\"RacerI" +
                "d\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"TeamId\" Type=\"Edm.Int32\" " +
                "Nullable=\"false\" /><NavigationProperty Name=\"Race\" Relationship=\"Formula1Service" +
                "Sample.Models.Formula1ServiceSample_Models_RaceResult_Race_Formula1ServiceSample" +
                "_Models_Race_RacePartner\" ToRole=\"Race\" FromRole=\"RacePartner\" /><NavigationProp" +
                "erty Name=\"Racer\" Relationship=\"Formula1ServiceSample.Models.Formula1ServiceSamp" +
                "le_Models_RaceResult_Racer_Formula1ServiceSample_Models_Racer_RacerPartner\" ToRo" +
                "le=\"Racer\" FromRole=\"RacerPartner\" /></EntityType><EntityType Name=\"Race\"><Key><" +
                "PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"fal" +
                "se\" /><Property Name=\"CircuitId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property N" +
                "ame=\"Date\" Type=\"Edm.DateTime\" Nullable=\"false\" /><NavigationProperty Name=\"Circ" +
                "uit\" Relationship=\"Formula1ServiceSample.Models.Formula1ServiceSample_Models_Rac" +
                "e_Circuit_Formula1ServiceSample_Models_Circuit_CircuitPartner\" ToRole=\"Circuit\" " +
                "FromRole=\"CircuitPartner\" /><NavigationProperty Name=\"RaceResults\" Relationship=" +
                "\"Formula1ServiceSample.Models.Formula1ServiceSample_Models_Race_RaceResults_Form" +
                "ula1ServiceSample_Models_RaceResult_RaceResultsPartner\" ToRole=\"RaceResults\" Fro" +
                "mRole=\"RaceResultsPartner\" /></EntityType><EntityType Name=\"Circuit\"><Key><Prope" +
                "rtyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /" +
                "><Property Name=\"Name\" Type=\"Edm.String\" /><Property Name=\"Country\" Type=\"Edm.St" +
                "ring\" /><NavigationProperty Name=\"Races\" Relationship=\"Formula1ServiceSample.Mod" +
                "els.Formula1ServiceSample_Models_Circuit_Races_Formula1ServiceSample_Models_Race" +
                "_RacesPartner\" ToRole=\"Races\" FromRole=\"RacesPartner\" /></EntityType><Associatio" +
                "n Name=\"Formula1ServiceSample_Models_Racer_RaceResults_Formula1ServiceSample_Mod" +
                "els_RaceResult_RaceResultsPartner\"><End Type=\"Formula1ServiceSample.Models.RaceR" +
                "esult\" Role=\"RaceResults\" Multiplicity=\"*\" /><End Type=\"Formula1ServiceSample.Mo" +
                "dels.Racer\" Role=\"RaceResultsPartner\" Multiplicity=\"0..1\" /></Association><Assoc" +
                "iation Name=\"Formula1ServiceSample_Models_RaceResult_Race_Formula1ServiceSample_" +
                "Models_Race_RacePartner\"><End Type=\"Formula1ServiceSample.Models.Race\" Role=\"Rac" +
                "e\" Multiplicity=\"0..1\" /><End Type=\"Formula1ServiceSample.Models.RaceResult\" Rol" +
                "e=\"RacePartner\" Multiplicity=\"0..1\" /></Association><Association Name=\"Formula1S" +
                "erviceSample_Models_RaceResult_Racer_Formula1ServiceSample_Models_Racer_RacerPar" +
                "tner\"><End Type=\"Formula1ServiceSample.Models.Racer\" Role=\"Racer\" Multiplicity=\"" +
                "0..1\" /><End Type=\"Formula1ServiceSample.Models.RaceResult\" Role=\"RacerPartner\" " +
                "Multiplicity=\"0..1\" /></Association><Association Name=\"Formula1ServiceSample_Mod" +
                "els_Race_Circuit_Formula1ServiceSample_Models_Circuit_CircuitPartner\"><End Type=" +
                "\"Formula1ServiceSample.Models.Circuit\" Role=\"Circuit\" Multiplicity=\"0..1\" /><End" +
                " Type=\"Formula1ServiceSample.Models.Race\" Role=\"CircuitPartner\" Multiplicity=\"0." +
                ".1\" /></Association><Association Name=\"Formula1ServiceSample_Models_Race_RaceRes" +
                "ults_Formula1ServiceSample_Models_RaceResult_RaceResultsPartner\"><End Type=\"Form" +
                "ula1ServiceSample.Models.RaceResult\" Role=\"RaceResults\" Multiplicity=\"*\" /><End " +
                "Type=\"Formula1ServiceSample.Models.Race\" Role=\"RaceResultsPartner\" Multiplicity=" +
                "\"0..1\" /></Association><Association Name=\"Formula1ServiceSample_Models_Circuit_R" +
                "aces_Formula1ServiceSample_Models_Race_RacesPartner\"><End Type=\"Formula1ServiceS" +
                "ample.Models.Race\" Role=\"Races\" Multiplicity=\"*\" /><End Type=\"Formula1ServiceSam" +
                "ple.Models.Circuit\" Role=\"RacesPartner\" Multiplicity=\"0..1\" /></Association></Sc" +
                "hema><Schema Namespace=\"Default\" xmlns=\"http://schemas.microsoft.com/ado/2009/11" +
                "/edm\"><EntityContainer Name=\"Container\" m:IsDefaultEntityContainer=\"true\"><Entit" +
                "ySet Name=\"Racer\" EntityType=\"Formula1ServiceSample.Models.Racer\" /><EntitySet N" +
                "ame=\"RaceResult\" EntityType=\"Formula1ServiceSample.Models.RaceResult\" /><EntityS" +
                "et Name=\"Race\" EntityType=\"Formula1ServiceSample.Models.Race\" /><EntitySet Name=" +
                "\"Circuit\" EntityType=\"Formula1ServiceSample.Models.Circuit\" /><AssociationSet Na" +
                "me=\"Formula1ServiceSample_Models_Racer_RaceResults_Formula1ServiceSample_Models_" +
                "RaceResult_RaceResultsPartnerSet\" Association=\"Formula1ServiceSample.Models.Form" +
                "ula1ServiceSample_Models_Racer_RaceResults_Formula1ServiceSample_Models_RaceResu" +
                "lt_RaceResultsPartner\"><End Role=\"RaceResultsPartner\" EntitySet=\"Racer\" /><End R" +
                "ole=\"RaceResults\" EntitySet=\"RaceResult\" /></AssociationSet><AssociationSet Name" +
                "=\"Formula1ServiceSample_Models_RaceResult_Race_Formula1ServiceSample_Models_Race" +
                "_RacePartnerSet\" Association=\"Formula1ServiceSample.Models.Formula1ServiceSample" +
                "_Models_RaceResult_Race_Formula1ServiceSample_Models_Race_RacePartner\"><End Role" +
                "=\"RacePartner\" EntitySet=\"RaceResult\" /><End Role=\"Race\" EntitySet=\"Race\" /></As" +
                "sociationSet><AssociationSet Name=\"Formula1ServiceSample_Models_RaceResult_Racer" +
                "_Formula1ServiceSample_Models_Racer_RacerPartnerSet\" Association=\"Formula1Servic" +
                "eSample.Models.Formula1ServiceSample_Models_RaceResult_Racer_Formula1ServiceSamp" +
                "le_Models_Racer_RacerPartner\"><End Role=\"RacerPartner\" EntitySet=\"RaceResult\" />" +
                "<End Role=\"Racer\" EntitySet=\"Racer\" /></AssociationSet><AssociationSet Name=\"For" +
                "mula1ServiceSample_Models_Race_Circuit_Formula1ServiceSample_Models_Circuit_Circ" +
                "uitPartnerSet\" Association=\"Formula1ServiceSample.Models.Formula1ServiceSample_M" +
                "odels_Race_Circuit_Formula1ServiceSample_Models_Circuit_CircuitPartner\"><End Rol" +
                "e=\"CircuitPartner\" EntitySet=\"Race\" /><End Role=\"Circuit\" EntitySet=\"Circuit\" />" +
                "</AssociationSet><AssociationSet Name=\"Formula1ServiceSample_Models_Race_RaceRes" +
                "ults_Formula1ServiceSample_Models_RaceResult_RaceResultsPartnerSet\" Association=" +
                "\"Formula1ServiceSample.Models.Formula1ServiceSample_Models_Race_RaceResults_Form" +
                "ula1ServiceSample_Models_RaceResult_RaceResultsPartner\"><End Role=\"RaceResultsPa" +
                "rtner\" EntitySet=\"Race\" /><End Role=\"RaceResults\" EntitySet=\"RaceResult\" /></Ass" +
                "ociationSet><AssociationSet Name=\"Formula1ServiceSample_Models_Circuit_Races_For" +
                "mula1ServiceSample_Models_Race_RacesPartnerSet\" Association=\"Formula1ServiceSamp" +
                "le.Models.Formula1ServiceSample_Models_Circuit_Races_Formula1ServiceSample_Model" +
                "s_Race_RacesPartner\"><End Role=\"RacesPartner\" EntitySet=\"Circuit\" /><End Role=\"R" +
                "aces\" EntitySet=\"Race\" /></AssociationSet></EntityContainer";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for Formula1ServiceSample.Models.Racer in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Racer")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Racer : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Racer object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Racer CreateRacer(int ID)
        {
            Racer racer = new Racer();
            racer.Id = ID;
            return racer;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Firstname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Firstname
        {
            get
            {
                return this._Firstname;
            }
            set
            {
                this.OnFirstnameChanging(value);
                this._Firstname = value;
                this.OnFirstnameChanged();
                this.OnPropertyChanged("Firstname");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Firstname;
        partial void OnFirstnameChanging(string value);
        partial void OnFirstnameChanged();
        /// <summary>
        /// There are no comments for Property Lastname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Lastname
        {
            get
            {
                return this._Lastname;
            }
            set
            {
                this.OnLastnameChanging(value);
                this._Lastname = value;
                this.OnLastnameChanged();
                this.OnPropertyChanged("Lastname");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Lastname;
        partial void OnLastnameChanging(string value);
        partial void OnLastnameChanged();
        /// <summary>
        /// There are no comments for Property Country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this.OnCountryChanging(value);
                this._Country = value;
                this.OnCountryChanged();
                this.OnPropertyChanged("Country");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Country;
        partial void OnCountryChanging(string value);
        partial void OnCountryChanged();
        /// <summary>
        /// There are no comments for Property Starts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Starts
        {
            get
            {
                return this._Starts;
            }
            set
            {
                this.OnStartsChanging(value);
                this._Starts = value;
                this.OnStartsChanged();
                this.OnPropertyChanged("Starts");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Starts;
        partial void OnStartsChanging(global::System.Nullable<int> value);
        partial void OnStartsChanged();
        /// <summary>
        /// There are no comments for Property Wins in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Wins
        {
            get
            {
                return this._Wins;
            }
            set
            {
                this.OnWinsChanging(value);
                this._Wins = value;
                this.OnWinsChanged();
                this.OnPropertyChanged("Wins");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Wins;
        partial void OnWinsChanging(global::System.Nullable<int> value);
        partial void OnWinsChanged();
        /// <summary>
        /// There are no comments for RaceResults in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RaceResult> RaceResults
        {
            get
            {
                return this._RaceResults;
            }
            set
            {
                this._RaceResults = value;
                this.OnPropertyChanged("RaceResults");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RaceResult> _RaceResults = new global::System.Data.Services.Client.DataServiceCollection<RaceResult>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Formula1ServiceSample.Models.RaceResult in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("RaceResult")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RaceResult : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RaceResult object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="raceId">Initial value of RaceId.</param>
        /// <param name="position">Initial value of Position.</param>
        /// <param name="racerId">Initial value of RacerId.</param>
        /// <param name="teamId">Initial value of TeamId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RaceResult CreateRaceResult(int ID, int raceId, int position, int racerId, int teamId)
        {
            RaceResult raceResult = new RaceResult();
            raceResult.Id = ID;
            raceResult.RaceId = raceId;
            raceResult.Position = position;
            raceResult.RacerId = racerId;
            raceResult.TeamId = teamId;
            return raceResult;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property RaceId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int RaceId
        {
            get
            {
                return this._RaceId;
            }
            set
            {
                this.OnRaceIdChanging(value);
                this._RaceId = value;
                this.OnRaceIdChanged();
                this.OnPropertyChanged("RaceId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _RaceId;
        partial void OnRaceIdChanging(int value);
        partial void OnRaceIdChanged();
        /// <summary>
        /// There are no comments for Property Position in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Position
        {
            get
            {
                return this._Position;
            }
            set
            {
                this.OnPositionChanging(value);
                this._Position = value;
                this.OnPositionChanged();
                this.OnPropertyChanged("Position");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Position;
        partial void OnPositionChanging(int value);
        partial void OnPositionChanged();
        /// <summary>
        /// There are no comments for Property Grid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Grid
        {
            get
            {
                return this._Grid;
            }
            set
            {
                this.OnGridChanging(value);
                this._Grid = value;
                this.OnGridChanged();
                this.OnPropertyChanged("Grid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Grid;
        partial void OnGridChanging(global::System.Nullable<int> value);
        partial void OnGridChanged();
        /// <summary>
        /// There are no comments for Property Points in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Points
        {
            get
            {
                return this._Points;
            }
            set
            {
                this.OnPointsChanging(value);
                this._Points = value;
                this.OnPointsChanged();
                this.OnPropertyChanged("Points");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Points;
        partial void OnPointsChanging(global::System.Nullable<decimal> value);
        partial void OnPointsChanged();
        /// <summary>
        /// There are no comments for Property RacerId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int RacerId
        {
            get
            {
                return this._RacerId;
            }
            set
            {
                this.OnRacerIdChanging(value);
                this._RacerId = value;
                this.OnRacerIdChanged();
                this.OnPropertyChanged("RacerId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _RacerId;
        partial void OnRacerIdChanging(int value);
        partial void OnRacerIdChanged();
        /// <summary>
        /// There are no comments for Property TeamId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int TeamId
        {
            get
            {
                return this._TeamId;
            }
            set
            {
                this.OnTeamIdChanging(value);
                this._TeamId = value;
                this.OnTeamIdChanged();
                this.OnPropertyChanged("TeamId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _TeamId;
        partial void OnTeamIdChanging(int value);
        partial void OnTeamIdChanged();
        /// <summary>
        /// There are no comments for Race in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Race Race
        {
            get
            {
                return this._Race;
            }
            set
            {
                this._Race = value;
                this.OnPropertyChanged("Race");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Race _Race;
        /// <summary>
        /// There are no comments for Racer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Racer Racer
        {
            get
            {
                return this._Racer;
            }
            set
            {
                this._Racer = value;
                this.OnPropertyChanged("Racer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Racer _Racer;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Formula1ServiceSample.Models.Race in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Race")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Race : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Race object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="circuitId">Initial value of CircuitId.</param>
        /// <param name="date">Initial value of Date.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Race CreateRace(int ID, int circuitId, global::System.DateTime date)
        {
            Race race = new Race();
            race.Id = ID;
            race.CircuitId = circuitId;
            race.Date = date;
            return race;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CircuitId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CircuitId
        {
            get
            {
                return this._CircuitId;
            }
            set
            {
                this.OnCircuitIdChanging(value);
                this._CircuitId = value;
                this.OnCircuitIdChanged();
                this.OnPropertyChanged("CircuitId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CircuitId;
        partial void OnCircuitIdChanging(int value);
        partial void OnCircuitIdChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Circuit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Circuit Circuit
        {
            get
            {
                return this._Circuit;
            }
            set
            {
                this._Circuit = value;
                this.OnPropertyChanged("Circuit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Circuit _Circuit;
        /// <summary>
        /// There are no comments for RaceResults in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RaceResult> RaceResults
        {
            get
            {
                return this._RaceResults;
            }
            set
            {
                this._RaceResults = value;
                this.OnPropertyChanged("RaceResults");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RaceResult> _RaceResults = new global::System.Data.Services.Client.DataServiceCollection<RaceResult>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Formula1ServiceSample.Models.Circuit in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Circuit")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Circuit : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Circuit object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Circuit CreateCircuit(int ID)
        {
            Circuit circuit = new Circuit();
            circuit.Id = ID;
            return circuit;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this.OnCountryChanging(value);
                this._Country = value;
                this.OnCountryChanged();
                this.OnPropertyChanged("Country");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Country;
        partial void OnCountryChanging(string value);
        partial void OnCountryChanged();
        /// <summary>
        /// There are no comments for Races in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Race> Races
        {
            get
            {
                return this._Races;
            }
            set
            {
                this._Races = value;
                this.OnPropertyChanged("Races");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Race> _Races = new global::System.Data.Services.Client.DataServiceCollection<Race>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
