//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chapter_6_CSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chapter_6_CSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AK,Aleutians East Borough,2744,19,0
        ///AK,Aleutians West Census Area,4659,34,0
        ///AK,Anchorage Municipality,286174,4542,1402
        ///AK,Bethel Census Area,17352,438,82
        ///AK,Bristol Bay Borough,881,6,2
        ///AK,Denali Borough,1851,22,0
        ///AK,Dillingham Census Area,4957,95,9
        ///AK,Fairbanks North Star Borough,98660,1828,339
        ///AK,Haines Borough,2399,20,4
        ///AK,Hoonah-Angoon Census Area,2127,22,2
        ///AK,Juneau City and Borough,30796,398,125
        ///AK,Kenai Peninsula Borough,54665,700,364
        ///AK,Ketchikan Gateway Borough,13005,190,93
        ///AK,Kodiak Is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Counties {
            get {
                return ResourceManager.GetString("Counties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AL,Alabama,52423,12/14/1819,Montgomery
        ///AK,Alaska,656425,1/3/1959,Juneau
        ///AZ,Arizona,114006,2/14/1912,Phoenix
        ///AR,Arkansas,53182,6/15/1836,Little Rock
        ///CA,California,163707,9/9/1850,Sacramento
        ///CO,Colorado,104100,8/1/1876,Denver
        ///CT,Connecticut,5544,1/9/1788,Hartford
        ///DE,Delaware,1954,12/7/1787,Dover
        ///FL,Florida,65758,3/3/1845,Tallahassee
        ///GA,Georgia,59441,1/2/1788,Atlanta
        ///HI,Hawaii,10932,8/21/1959,Honolulu
        ///ID,Idaho,83574,7/3/1890,Boise
        ///IL,Illinois,57918,12/3/1818,Springfield
        ///IN,Indiana,36420,12/11/1816 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string States {
            get {
                return ResourceManager.GetString("States", resourceCulture);
            }
        }
    }
}
