--应用事务
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN tra01
UPDATE CGoods
SET g_name = '婴儿秋套装'
WHERE g_id = 'SP10001'
--COMMIT TRAN tra01
WAITFOR DELAY '00:00:10'
ROLLBACK TRAN tra01
SELECT * FROM CGoods
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN tra02
SELECT * FROM CGoods 
IF @@ROWCOUNT > 0
BEGIN
  WAITFOR DELAY '00:00:10' 
  SELECT * FROM CGoods   
END
COMMIT TRAN tra02
