//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 01.11.2009 18:53:03
namespace WCFRegistration.RegistrationDataService.EventRegistrationModel
{
    
    /// <summary>
    /// There are no comments for EventRegistrationEntities in the schema.
    /// </summary>
    public partial class EventRegistrationEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new EventRegistrationEntities object.
        /// </summary>
        public EventRegistrationEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.EntityModel.Emitters.EntityContainerEmitter", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("EventRegistrationModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("WCFRegistration.RegistrationDataService.EventRegistrationModel", typeName.Substring(22)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.EntityModel.Emitters.EntityContainerEmitter", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("WCFRegistration.RegistrationDataService.EventRegistrationModel", global::System.StringComparison.Ordinal))
            {
                return string.Concat("EventRegistrationModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Attendees in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<Attendee> Attendees
        {
            get
            {
                if ((this._Attendees == null))
                {
                    this._Attendees = base.CreateQuery<Attendee>("Attendees");
                }
                return this._Attendees;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Attendee> _Attendees;
        /// <summary>
        /// There are no comments for Events in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<Event> Events
        {
            get
            {
                if ((this._Events == null))
                {
                    this._Events = base.CreateQuery<Event>("Events");
                }
                return this._Events;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Event> _Events;
        /// <summary>
        /// There are no comments for Attendees in the schema.
        /// </summary>
        public void AddToAttendees(Attendee attendee)
        {
            base.AddObject("Attendees", attendee);
        }
        /// <summary>
        /// There are no comments for Events in the schema.
        /// </summary>
        public void AddToEvents(Event @event)
        {
            base.AddObject("Events", @event);
        }
    }
    /// <summary>
    /// There are no comments for EventRegistrationModel.Attendee in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Attendee
    {
        /// <summary>
        /// Create a new Attendee object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="eventId">Initial value of EventId.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Attendee CreateAttendee(int ID, int eventId, string name)
        {
            Attendee attendee = new Attendee();
            attendee.Id = ID;
            attendee.EventId = eventId;
            attendee.Name = name;
            return attendee;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property EventId in the schema.
        /// </summary>
        public int EventId
        {
            get
            {
                return this._EventId;
            }
            set
            {
                this.OnEventIdChanging(value);
                this._EventId = value;
                this.OnEventIdChanged();
            }
        }
        private int _EventId;
        partial void OnEventIdChanging(int value);
        partial void OnEventIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
            }
        }
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Company in the schema.
        /// </summary>
        public string Company
        {
            get
            {
                return this._Company;
            }
            set
            {
                this.OnCompanyChanging(value);
                this._Company = value;
                this.OnCompanyChanged();
            }
        }
        private string _Company;
        partial void OnCompanyChanging(string value);
        partial void OnCompanyChanged();
        /// <summary>
        /// There are no comments for Property RegistrationCode in the schema.
        /// </summary>
        public string RegistrationCode
        {
            get
            {
                return this._RegistrationCode;
            }
            set
            {
                this.OnRegistrationCodeChanging(value);
                this._RegistrationCode = value;
                this.OnRegistrationCodeChanged();
            }
        }
        private string _RegistrationCode;
        partial void OnRegistrationCodeChanging(string value);
        partial void OnRegistrationCodeChanged();
        /// <summary>
        /// There are no comments for Event in the schema.
        /// </summary>
        public Event Event
        {
            get
            {
                return this._Event;
            }
            set
            {
                this._Event = value;
            }
        }
        private Event _Event;
    }
    /// <summary>
    /// There are no comments for EventRegistrationModel.Event in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Event
    {
        /// <summary>
        /// Create a new Event object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="dateFrom">Initial value of DateFrom.</param>
        /// <param name="dateTo">Initial value of DateTo.</param>
        public static Event CreateEvent(int ID, string name, global::System.DateTime dateFrom, global::System.DateTime dateTo)
        {
            Event @event = new Event();
            @event.Id = ID;
            @event.Name = name;
            @event.DateFrom = dateFrom;
            @event.DateTo = dateTo;
            return @event;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property DateFrom in the schema.
        /// </summary>
        public global::System.DateTime DateFrom
        {
            get
            {
                return this._DateFrom;
            }
            set
            {
                this.OnDateFromChanging(value);
                this._DateFrom = value;
                this.OnDateFromChanged();
            }
        }
        private global::System.DateTime _DateFrom;
        partial void OnDateFromChanging(global::System.DateTime value);
        partial void OnDateFromChanged();
        /// <summary>
        /// There are no comments for Property DateTo in the schema.
        /// </summary>
        public global::System.DateTime DateTo
        {
            get
            {
                return this._DateTo;
            }
            set
            {
                this.OnDateToChanging(value);
                this._DateTo = value;
                this.OnDateToChanged();
            }
        }
        private global::System.DateTime _DateTo;
        partial void OnDateToChanging(global::System.DateTime value);
        partial void OnDateToChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Attendees in the schema.
        /// </summary>
        public global::System.Collections.ObjectModel.Collection<Attendee> Attendees
        {
            get
            {
                return this._Attendees;
            }
            set
            {
                if ((value != null))
                {
                    this._Attendees = value;
                }
            }
        }
        private global::System.Collections.ObjectModel.Collection<Attendee> _Attendees = new global::System.Collections.ObjectModel.Collection<Attendee>();
    }
}
