#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcedureQuery
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="db_TomeTwo")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClassesDataContext() : 
				base(global::ProcedureQuery.Properties.Settings.Default.db_TomeTwoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.P_queryWarehouseInfo")]
		public ISingleResult<P_queryWarehouseInfo_个结果> P_queryWarehouseInfo([Parameter(DbType="VarChar(20)")] string helpCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), helpCode);
			return ((ISingleResult<P_queryWarehouseInfo_个结果>)(result.ReturnValue));
		}
	}
	
	public partial class P_queryWarehouseInfo_个结果
	{
		
		private int _ID;
		
		private string _WareHouseCode;
		
		private string _HelpCode;
		
		private string _ShortName;
		
		private string _WareHouseName;
		
		private string _Location;
		
		private System.Nullable<double> _Area;
		
		private string _Memo;
		
		public P_queryWarehouseInfo_个结果()
		{
		}
		
		[Column(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_WareHouseCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string WareHouseCode
		{
			get
			{
				return this._WareHouseCode;
			}
			set
			{
				if ((this._WareHouseCode != value))
				{
					this._WareHouseCode = value;
				}
			}
		}
		
		[Column(Storage="_HelpCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string HelpCode
		{
			get
			{
				return this._HelpCode;
			}
			set
			{
				if ((this._HelpCode != value))
				{
					this._HelpCode = value;
				}
			}
		}
		
		[Column(Storage="_ShortName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ShortName
		{
			get
			{
				return this._ShortName;
			}
			set
			{
				if ((this._ShortName != value))
				{
					this._ShortName = value;
				}
			}
		}
		
		[Column(Storage="_WareHouseName", DbType="VarChar(50)")]
		public string WareHouseName
		{
			get
			{
				return this._WareHouseName;
			}
			set
			{
				if ((this._WareHouseName != value))
				{
					this._WareHouseName = value;
				}
			}
		}
		
		[Column(Storage="_Location", DbType="VarChar(50)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this._Location = value;
				}
			}
		}
		
		[Column(Storage="_Area", DbType="Float")]
		public System.Nullable<double> Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this._Area = value;
				}
			}
		}
		
		[Column(Storage="_Memo", DbType="VarChar(200)")]
		public string Memo
		{
			get
			{
				return this._Memo;
			}
			set
			{
				if ((this._Memo != value))
				{
					this._Memo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
