//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.PropertyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadPropertyInformation", Namespace="http://pro-csharp/")]
    [System.SerializableAttribute()]
    public partial class UploadPropertyInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ownerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double askingPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                if ((object.ReferenceEquals(this.ownerField, value) != true)) {
                    this.ownerField = value;
                    this.RaisePropertyChanged("owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double askingPrice {
            get {
                return this.askingPriceField;
            }
            set {
                if ((this.askingPriceField.Equals(value) != true)) {
                    this.askingPriceField = value;
                    this.RaisePropertyChanged("askingPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pro-csharp/", ConfigurationName="PropertyService.IProperty")]
    public interface IProperty {
        
        // CODEGEN: Generating message contract since the operation UploadPropertyInformation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://pro-csharp/IProperty/UploadPropertyInformation", ReplyAction="http://pro-csharp/IProperty/UploadPropertyInformationResponse")]
        ClientApp.PropertyService.UploadPropertyInformationResponse UploadPropertyInformation(ClientApp.PropertyService.UploadPropertyInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://pro-csharp/IProperty/UploadRoomInformation")]
        void UploadRoomInformation(System.Guid propertyId, string roomName, double width, double depth);
        
        // CODEGEN: Generating message contract since the operation DetailsComplete is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://pro-csharp/IProperty/DetailsComplete")]
        void DetailsComplete(ClientApp.PropertyService.DetailsComplete request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadPropertyInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pro-csharp/", Order=0)]
        public ClientApp.PropertyService.UploadPropertyInformation UploadPropertyInformation;
        
        public UploadPropertyInformationRequest() {
        }
        
        public UploadPropertyInformationRequest(ClientApp.PropertyService.UploadPropertyInformation UploadPropertyInformation) {
            this.UploadPropertyInformation = UploadPropertyInformation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadPropertyInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public System.Nullable<System.Guid> guid;
        
        public UploadPropertyInformationResponse() {
        }
        
        public UploadPropertyInformationResponse(System.Nullable<System.Guid> guid) {
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DetailsComplete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public System.Nullable<System.Guid> guid;
        
        public DetailsComplete() {
        }
        
        public DetailsComplete(System.Nullable<System.Guid> guid) {
            this.guid = guid;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPropertyChannel : ClientApp.PropertyService.IProperty, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PropertyClient : System.ServiceModel.ClientBase<ClientApp.PropertyService.IProperty>, ClientApp.PropertyService.IProperty {
        
        public PropertyClient() {
        }
        
        public PropertyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PropertyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PropertyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PropertyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApp.PropertyService.UploadPropertyInformationResponse ClientApp.PropertyService.IProperty.UploadPropertyInformation(ClientApp.PropertyService.UploadPropertyInformationRequest request) {
            return base.Channel.UploadPropertyInformation(request);
        }
        
        public System.Nullable<System.Guid> UploadPropertyInformation(ClientApp.PropertyService.UploadPropertyInformation UploadPropertyInformation1) {
            ClientApp.PropertyService.UploadPropertyInformationRequest inValue = new ClientApp.PropertyService.UploadPropertyInformationRequest();
            inValue.UploadPropertyInformation = UploadPropertyInformation1;
            ClientApp.PropertyService.UploadPropertyInformationResponse retVal = ((ClientApp.PropertyService.IProperty)(this)).UploadPropertyInformation(inValue);
            return retVal.guid;
        }
        
        public void UploadRoomInformation(System.Guid propertyId, string roomName, double width, double depth) {
            base.Channel.UploadRoomInformation(propertyId, roomName, width, depth);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ClientApp.PropertyService.IProperty.DetailsComplete(ClientApp.PropertyService.DetailsComplete request) {
            base.Channel.DetailsComplete(request);
        }
        
        public void DetailsComplete(System.Nullable<System.Guid> guid) {
            ClientApp.PropertyService.DetailsComplete inValue = new ClientApp.PropertyService.DetailsComplete();
            inValue.guid = guid;
            ((ClientApp.PropertyService.IProperty)(this)).DetailsComplete(inValue);
        }
    }
}
