#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiTableJoin
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="db_TomeTwo")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClassesDataContext() : 
				base(global::MultiTableJoin.Properties.Settings.Default.db_TomeTwoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SaleContent> SaleContent
		{
			get
			{
				return this.GetTable<SaleContent>();
			}
		}
		
		public System.Data.Linq.Table<SaleDetail> SaleDetail
		{
			get
			{
				return this.GetTable<SaleDetail>();
			}
		}
		
		public System.Data.Linq.Table<ProductInfo> ProductInfo
		{
			get
			{
				return this.GetTable<ProductInfo>();
			}
		}
		
		public System.Data.Linq.Table<EmployeeInfo> EmployeeInfo
		{
			get
			{
				return this.GetTable<EmployeeInfo>();
			}
		}
		
		public System.Data.Linq.Table<WarehouseInfo> WarehouseInfo
		{
			get
			{
				return this.GetTable<WarehouseInfo>();
			}
		}
		
		public System.Data.Linq.Table<ClientInfo> ClientInfo
		{
			get
			{
				return this.GetTable<ClientInfo>();
			}
		}
	}
	
	[Table(Name="dbo.SaleContent")]
	public partial class SaleContent
	{
		
		private int _ID;
		
		private string _SaleBillCode;
		
		private string _SaleMan;
		
		private System.DateTime _SaleDate;
		
		private string _ClientCode;
		
		private string _WareHouse;
		
		private string _PayMode;
		
		private string _InvoiceType;
		
		private string _InvoiceCode;
		
		private string _Memo;
		
		private string _Operator;
		
		private System.Nullable<System.DateTime> _OperateDate;
		
		private System.Nullable<bool> _AuditFlag;
		
		public SaleContent()
		{
		}
		
		[Column(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_SaleBillCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SaleBillCode
		{
			get
			{
				return this._SaleBillCode;
			}
			set
			{
				if ((this._SaleBillCode != value))
				{
					this._SaleBillCode = value;
				}
			}
		}
		
		[Column(Storage="_SaleMan", DbType="VarChar(20)")]
		public string SaleMan
		{
			get
			{
				return this._SaleMan;
			}
			set
			{
				if ((this._SaleMan != value))
				{
					this._SaleMan = value;
				}
			}
		}
		
		[Column(Storage="_SaleDate", DbType="DateTime NOT NULL")]
		public System.DateTime SaleDate
		{
			get
			{
				return this._SaleDate;
			}
			set
			{
				if ((this._SaleDate != value))
				{
					this._SaleDate = value;
				}
			}
		}
		
		[Column(Storage="_ClientCode", DbType="VarChar(20)")]
		public string ClientCode
		{
			get
			{
				return this._ClientCode;
			}
			set
			{
				if ((this._ClientCode != value))
				{
					this._ClientCode = value;
				}
			}
		}
		
		[Column(Storage="_WareHouse", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string WareHouse
		{
			get
			{
				return this._WareHouse;
			}
			set
			{
				if ((this._WareHouse != value))
				{
					this._WareHouse = value;
				}
			}
		}
		
		[Column(Storage="_PayMode", DbType="VarChar(20)")]
		public string PayMode
		{
			get
			{
				return this._PayMode;
			}
			set
			{
				if ((this._PayMode != value))
				{
					this._PayMode = value;
				}
			}
		}
		
		[Column(Storage="_InvoiceType", DbType="VarChar(20)")]
		public string InvoiceType
		{
			get
			{
				return this._InvoiceType;
			}
			set
			{
				if ((this._InvoiceType != value))
				{
					this._InvoiceType = value;
				}
			}
		}
		
		[Column(Storage="_InvoiceCode", DbType="VarChar(20)")]
		public string InvoiceCode
		{
			get
			{
				return this._InvoiceCode;
			}
			set
			{
				if ((this._InvoiceCode != value))
				{
					this._InvoiceCode = value;
				}
			}
		}
		
		[Column(Storage="_Memo", DbType="VarChar(100)")]
		public string Memo
		{
			get
			{
				return this._Memo;
			}
			set
			{
				if ((this._Memo != value))
				{
					this._Memo = value;
				}
			}
		}
		
		[Column(Storage="_Operator", DbType="VarChar(20)")]
		public string Operator
		{
			get
			{
				return this._Operator;
			}
			set
			{
				if ((this._Operator != value))
				{
					this._Operator = value;
				}
			}
		}
		
		[Column(Storage="_OperateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> OperateDate
		{
			get
			{
				return this._OperateDate;
			}
			set
			{
				if ((this._OperateDate != value))
				{
					this._OperateDate = value;
				}
			}
		}
		
		[Column(Storage="_AuditFlag", DbType="Bit")]
		public System.Nullable<bool> AuditFlag
		{
			get
			{
				return this._AuditFlag;
			}
			set
			{
				if ((this._AuditFlag != value))
				{
					this._AuditFlag = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.SaleDetail")]
	public partial class SaleDetail
	{
		
		private int _ID;
		
		private string _SaleBillCode;
		
		private string _ProductCode;
		
		private int _Quantity;
		
		private double _Price;
		
		private string _Memo;
		
		private System.Nullable<double> _Cost;
		
		public SaleDetail()
		{
		}
		
		[Column(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_SaleBillCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SaleBillCode
		{
			get
			{
				return this._SaleBillCode;
			}
			set
			{
				if ((this._SaleBillCode != value))
				{
					this._SaleBillCode = value;
				}
			}
		}
		
		[Column(Storage="_ProductCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this._ProductCode = value;
				}
			}
		}
		
		[Column(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[Column(Storage="_Price", DbType="Float NOT NULL")]
		public double Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[Column(Storage="_Memo", DbType="VarChar(100)")]
		public string Memo
		{
			get
			{
				return this._Memo;
			}
			set
			{
				if ((this._Memo != value))
				{
					this._Memo = value;
				}
			}
		}
		
		[Column(Storage="_Cost", DbType="Float")]
		public System.Nullable<double> Cost
		{
			get
			{
				return this._Cost;
			}
			set
			{
				if ((this._Cost != value))
				{
					this._Cost = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.ProductInfo")]
	public partial class ProductInfo
	{
		
		private int _ID;
		
		private string _ProductCode;
		
		private string _HelpCode;
		
		private string _ShortName;
		
		private string _ProductName;
		
		private string _Specs;
		
		private string _ProductType;
		
		private string _Yieldly;
		
		private string _Unit;
		
		private string _WareHouse;
		
		private System.Nullable<int> _MaxStore;
		
		private System.Nullable<int> _MinStore;
		
		private System.Nullable<bool> _IsStop;
		
		private System.Nullable<double> _RetailPrice;
		
		private System.Nullable<double> _TradePrice;
		
		private System.Nullable<double> _MinimumPrice;
		
		private System.Nullable<double> _AdrisePrice;
		
		private System.Nullable<double> _CurMarketingPrice;
		
		private string _Operator;
		
		private System.Nullable<System.DateTime> _OperateDate;
		
		public ProductInfo()
		{
		}
		
		[Column(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_ProductCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this._ProductCode = value;
				}
			}
		}
		
		[Column(Storage="_HelpCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string HelpCode
		{
			get
			{
				return this._HelpCode;
			}
			set
			{
				if ((this._HelpCode != value))
				{
					this._HelpCode = value;
				}
			}
		}
		
		[Column(Storage="_ShortName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ShortName
		{
			get
			{
				return this._ShortName;
			}
			set
			{
				if ((this._ShortName != value))
				{
					this._ShortName = value;
				}
			}
		}
		
		[Column(Storage="_ProductName", DbType="VarChar(100)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[Column(Storage="_Specs", DbType="VarChar(50)")]
		public string Specs
		{
			get
			{
				return this._Specs;
			}
			set
			{
				if ((this._Specs != value))
				{
					this._Specs = value;
				}
			}
		}
		
		[Column(Storage="_ProductType", DbType="VarChar(20)")]
		public string ProductType
		{
			get
			{
				return this._ProductType;
			}
			set
			{
				if ((this._ProductType != value))
				{
					this._ProductType = value;
				}
			}
		}
		
		[Column(Storage="_Yieldly", DbType="VarChar(100)")]
		public string Yieldly
		{
			get
			{
				return this._Yieldly;
			}
			set
			{
				if ((this._Yieldly != value))
				{
					this._Yieldly = value;
				}
			}
		}
		
		[Column(Storage="_Unit", DbType="VarChar(10)")]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this._Unit = value;
				}
			}
		}
		
		[Column(Storage="_WareHouse", DbType="VarChar(20)")]
		public string WareHouse
		{
			get
			{
				return this._WareHouse;
			}
			set
			{
				if ((this._WareHouse != value))
				{
					this._WareHouse = value;
				}
			}
		}
		
		[Column(Storage="_MaxStore", DbType="Int")]
		public System.Nullable<int> MaxStore
		{
			get
			{
				return this._MaxStore;
			}
			set
			{
				if ((this._MaxStore != value))
				{
					this._MaxStore = value;
				}
			}
		}
		
		[Column(Storage="_MinStore", DbType="Int")]
		public System.Nullable<int> MinStore
		{
			get
			{
				return this._MinStore;
			}
			set
			{
				if ((this._MinStore != value))
				{
					this._MinStore = value;
				}
			}
		}
		
		[Column(Storage="_IsStop", DbType="Bit")]
		public System.Nullable<bool> IsStop
		{
			get
			{
				return this._IsStop;
			}
			set
			{
				if ((this._IsStop != value))
				{
					this._IsStop = value;
				}
			}
		}
		
		[Column(Storage="_RetailPrice", DbType="Float")]
		public System.Nullable<double> RetailPrice
		{
			get
			{
				return this._RetailPrice;
			}
			set
			{
				if ((this._RetailPrice != value))
				{
					this._RetailPrice = value;
				}
			}
		}
		
		[Column(Storage="_TradePrice", DbType="Float")]
		public System.Nullable<double> TradePrice
		{
			get
			{
				return this._TradePrice;
			}
			set
			{
				if ((this._TradePrice != value))
				{
					this._TradePrice = value;
				}
			}
		}
		
		[Column(Storage="_MinimumPrice", DbType="Float")]
		public System.Nullable<double> MinimumPrice
		{
			get
			{
				return this._MinimumPrice;
			}
			set
			{
				if ((this._MinimumPrice != value))
				{
					this._MinimumPrice = value;
				}
			}
		}
		
		[Column(Storage="_AdrisePrice", DbType="Float")]
		public System.Nullable<double> AdrisePrice
		{
			get
			{
				return this._AdrisePrice;
			}
			set
			{
				if ((this._AdrisePrice != value))
				{
					this._AdrisePrice = value;
				}
			}
		}
		
		[Column(Storage="_CurMarketingPrice", DbType="Float")]
		public System.Nullable<double> CurMarketingPrice
		{
			get
			{
				return this._CurMarketingPrice;
			}
			set
			{
				if ((this._CurMarketingPrice != value))
				{
					this._CurMarketingPrice = value;
				}
			}
		}
		
		[Column(Storage="_Operator", DbType="VarChar(20)")]
		public string Operator
		{
			get
			{
				return this._Operator;
			}
			set
			{
				if ((this._Operator != value))
				{
					this._Operator = value;
				}
			}
		}
		
		[Column(Storage="_OperateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> OperateDate
		{
			get
			{
				return this._OperateDate;
			}
			set
			{
				if ((this._OperateDate != value))
				{
					this._OperateDate = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.EmployeeInfo")]
	public partial class EmployeeInfo
	{
		
		private int _ID;
		
		private string _EmployeeCode;
		
		private string _HelpCode;
		
		private string _Name;
		
		private string _Sex;
		
		private System.Nullable<System.DateTime> _Birthday;
		
		private string _Handset;
		
		private string _Tel;
		
		private string _Addr;
		
		private string _IDCard;
		
		private string _EMail;
		
		private string _Operator;
		
		private System.Nullable<System.DateTime> _OperateDate;
		
		public EmployeeInfo()
		{
		}
		
		[Column(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_EmployeeCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string EmployeeCode
		{
			get
			{
				return this._EmployeeCode;
			}
			set
			{
				if ((this._EmployeeCode != value))
				{
					this._EmployeeCode = value;
				}
			}
		}
		
		[Column(Storage="_HelpCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string HelpCode
		{
			get
			{
				return this._HelpCode;
			}
			set
			{
				if ((this._HelpCode != value))
				{
					this._HelpCode = value;
				}
			}
		}
		
		[Column(Storage="_Name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[Column(Storage="_Sex", DbType="VarChar(10)")]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this._Sex = value;
				}
			}
		}
		
		[Column(Storage="_Birthday", DbType="DateTime")]
		public System.Nullable<System.DateTime> Birthday
		{
			get
			{
				return this._Birthday;
			}
			set
			{
				if ((this._Birthday != value))
				{
					this._Birthday = value;
				}
			}
		}
		
		[Column(Storage="_Handset", DbType="VarChar(20)")]
		public string Handset
		{
			get
			{
				return this._Handset;
			}
			set
			{
				if ((this._Handset != value))
				{
					this._Handset = value;
				}
			}
		}
		
		[Column(Storage="_Tel", DbType="VarChar(20)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this._Tel = value;
				}
			}
		}
		
		[Column(Storage="_Addr", DbType="VarChar(100)")]
		public string Addr
		{
			get
			{
				return this._Addr;
			}
			set
			{
				if ((this._Addr != value))
				{
					this._Addr = value;
				}
			}
		}
		
		[Column(Storage="_IDCard", DbType="VarChar(22)")]
		public string IDCard
		{
			get
			{
				return this._IDCard;
			}
			set
			{
				if ((this._IDCard != value))
				{
					this._IDCard = value;
				}
			}
		}
		
		[Column(Storage="_EMail", DbType="VarChar(50)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this._EMail = value;
				}
			}
		}
		
		[Column(Storage="_Operator", DbType="VarChar(20)")]
		public string Operator
		{
			get
			{
				return this._Operator;
			}
			set
			{
				if ((this._Operator != value))
				{
					this._Operator = value;
				}
			}
		}
		
		[Column(Storage="_OperateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> OperateDate
		{
			get
			{
				return this._OperateDate;
			}
			set
			{
				if ((this._OperateDate != value))
				{
					this._OperateDate = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.WarehouseInfo")]
	public partial class WarehouseInfo
	{
		
		private int _ID;
		
		private string _WareHouseCode;
		
		private string _HelpCode;
		
		private string _ShortName;
		
		private string _WareHouseName;
		
		private string _Location;
		
		private System.Nullable<double> _Area;
		
		private string _Memo;
		
		public WarehouseInfo()
		{
		}
		
		[Column(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_WareHouseCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string WareHouseCode
		{
			get
			{
				return this._WareHouseCode;
			}
			set
			{
				if ((this._WareHouseCode != value))
				{
					this._WareHouseCode = value;
				}
			}
		}
		
		[Column(Storage="_HelpCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string HelpCode
		{
			get
			{
				return this._HelpCode;
			}
			set
			{
				if ((this._HelpCode != value))
				{
					this._HelpCode = value;
				}
			}
		}
		
		[Column(Storage="_ShortName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ShortName
		{
			get
			{
				return this._ShortName;
			}
			set
			{
				if ((this._ShortName != value))
				{
					this._ShortName = value;
				}
			}
		}
		
		[Column(Storage="_WareHouseName", DbType="VarChar(50)")]
		public string WareHouseName
		{
			get
			{
				return this._WareHouseName;
			}
			set
			{
				if ((this._WareHouseName != value))
				{
					this._WareHouseName = value;
				}
			}
		}
		
		[Column(Storage="_Location", DbType="VarChar(50)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this._Location = value;
				}
			}
		}
		
		[Column(Storage="_Area", DbType="Float")]
		public System.Nullable<double> Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this._Area = value;
				}
			}
		}
		
		[Column(Storage="_Memo", DbType="VarChar(200)")]
		public string Memo
		{
			get
			{
				return this._Memo;
			}
			set
			{
				if ((this._Memo != value))
				{
					this._Memo = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.ClientInfo")]
	public partial class ClientInfo
	{
		
		private int _ID;
		
		private string _ClientCode;
		
		private string _HelpCode;
		
		private string _ShortName;
		
		private string _CompanyName;
		
		private string _CompanyAddr;
		
		private string _CompanyTel;
		
		private string _Linkman;
		
		private string _LinkTel;
		
		private string _Fax;
		
		private string _ClientType;
		
		private string _ClientKind;
		
		private string _ClientArea;
		
		private string _ClientProperty;
		
		private string _PostAddr;
		
		private string _PostalCode;
		
		private string _Bank;
		
		private string _Accounts;
		
		private string _TaxNum;
		
		private string _EMail;
		
		private string _HomePage;
		
		private string _Memo;
		
		private string _Operator;
		
		private System.Nullable<System.DateTime> _OperateDate;
		
		public ClientInfo()
		{
		}
		
		[Column(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_ClientCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ClientCode
		{
			get
			{
				return this._ClientCode;
			}
			set
			{
				if ((this._ClientCode != value))
				{
					this._ClientCode = value;
				}
			}
		}
		
		[Column(Storage="_HelpCode", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string HelpCode
		{
			get
			{
				return this._HelpCode;
			}
			set
			{
				if ((this._HelpCode != value))
				{
					this._HelpCode = value;
				}
			}
		}
		
		[Column(Storage="_ShortName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ShortName
		{
			get
			{
				return this._ShortName;
			}
			set
			{
				if ((this._ShortName != value))
				{
					this._ShortName = value;
				}
			}
		}
		
		[Column(Storage="_CompanyName", DbType="VarChar(100)")]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this._CompanyName = value;
				}
			}
		}
		
		[Column(Storage="_CompanyAddr", DbType="VarChar(100)")]
		public string CompanyAddr
		{
			get
			{
				return this._CompanyAddr;
			}
			set
			{
				if ((this._CompanyAddr != value))
				{
					this._CompanyAddr = value;
				}
			}
		}
		
		[Column(Storage="_CompanyTel", DbType="VarChar(20)")]
		public string CompanyTel
		{
			get
			{
				return this._CompanyTel;
			}
			set
			{
				if ((this._CompanyTel != value))
				{
					this._CompanyTel = value;
				}
			}
		}
		
		[Column(Storage="_Linkman", DbType="VarChar(20)")]
		public string Linkman
		{
			get
			{
				return this._Linkman;
			}
			set
			{
				if ((this._Linkman != value))
				{
					this._Linkman = value;
				}
			}
		}
		
		[Column(Storage="_LinkTel", DbType="VarChar(20)")]
		public string LinkTel
		{
			get
			{
				return this._LinkTel;
			}
			set
			{
				if ((this._LinkTel != value))
				{
					this._LinkTel = value;
				}
			}
		}
		
		[Column(Storage="_Fax", DbType="VarChar(20)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[Column(Storage="_ClientType", DbType="VarChar(20)")]
		public string ClientType
		{
			get
			{
				return this._ClientType;
			}
			set
			{
				if ((this._ClientType != value))
				{
					this._ClientType = value;
				}
			}
		}
		
		[Column(Storage="_ClientKind", DbType="VarChar(20)")]
		public string ClientKind
		{
			get
			{
				return this._ClientKind;
			}
			set
			{
				if ((this._ClientKind != value))
				{
					this._ClientKind = value;
				}
			}
		}
		
		[Column(Storage="_ClientArea", DbType="VarChar(50)")]
		public string ClientArea
		{
			get
			{
				return this._ClientArea;
			}
			set
			{
				if ((this._ClientArea != value))
				{
					this._ClientArea = value;
				}
			}
		}
		
		[Column(Storage="_ClientProperty", DbType="VarChar(20)")]
		public string ClientProperty
		{
			get
			{
				return this._ClientProperty;
			}
			set
			{
				if ((this._ClientProperty != value))
				{
					this._ClientProperty = value;
				}
			}
		}
		
		[Column(Storage="_PostAddr", DbType="VarChar(100)")]
		public string PostAddr
		{
			get
			{
				return this._PostAddr;
			}
			set
			{
				if ((this._PostAddr != value))
				{
					this._PostAddr = value;
				}
			}
		}
		
		[Column(Storage="_PostalCode", DbType="VarChar(20)")]
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				if ((this._PostalCode != value))
				{
					this._PostalCode = value;
				}
			}
		}
		
		[Column(Storage="_Bank", DbType="VarChar(50)")]
		public string Bank
		{
			get
			{
				return this._Bank;
			}
			set
			{
				if ((this._Bank != value))
				{
					this._Bank = value;
				}
			}
		}
		
		[Column(Storage="_Accounts", DbType="VarChar(20)")]
		public string Accounts
		{
			get
			{
				return this._Accounts;
			}
			set
			{
				if ((this._Accounts != value))
				{
					this._Accounts = value;
				}
			}
		}
		
		[Column(Storage="_TaxNum", DbType="VarChar(20)")]
		public string TaxNum
		{
			get
			{
				return this._TaxNum;
			}
			set
			{
				if ((this._TaxNum != value))
				{
					this._TaxNum = value;
				}
			}
		}
		
		[Column(Storage="_EMail", DbType="VarChar(100)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this._EMail = value;
				}
			}
		}
		
		[Column(Storage="_HomePage", DbType="VarChar(100)")]
		public string HomePage
		{
			get
			{
				return this._HomePage;
			}
			set
			{
				if ((this._HomePage != value))
				{
					this._HomePage = value;
				}
			}
		}
		
		[Column(Storage="_Memo", DbType="VarChar(200)")]
		public string Memo
		{
			get
			{
				return this._Memo;
			}
			set
			{
				if ((this._Memo != value))
				{
					this._Memo = value;
				}
			}
		}
		
		[Column(Storage="_Operator", DbType="VarChar(20)")]
		public string Operator
		{
			get
			{
				return this._Operator;
			}
			set
			{
				if ((this._Operator != value))
				{
					this._Operator = value;
				}
			}
		}
		
		[Column(Storage="_OperateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> OperateDate
		{
			get
			{
				return this._OperateDate;
			}
			set
			{
				if ((this._OperateDate != value))
				{
					this._OperateDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
