#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionQuery
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="db_TomeTwo")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClassesDataContext() : 
				base(global::FunctionQuery.Properties.Settings.Default.db_TomeTwoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EmployeeInfo> EmployeeInfo
		{
			get
			{
				return this.GetTable<EmployeeInfo>();
			}
		}

        [Function(Name = "dbo.F_GetSex", IsComposable = true)]
        public string F_GetSex([Parameter(Name = "SexFlag", DbType = "VarChar(10)")] string sexFlag)
        {
            return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sexFlag).ReturnValue));
        }
	}
	
	[Table(Name="dbo.EmployeeInfo")]
	public partial class EmployeeInfo
	{
		
		private int _ID;
		
		private string _EmployeeCode;
		
		private string _HelpCode;
		
		private string _Name;
		
		private string _Sex;
		
		private System.Nullable<System.DateTime> _Birthday;
		
		private string _Handset;
		
		private string _Tel;
		
		private string _Addr;
		
		private string _IDCard;
		
		private string _EMail;
		
		private string _Operator;
		
		private System.Nullable<System.DateTime> _OperateDate;
		
		public EmployeeInfo()
		{
		}
		
		[Column(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_EmployeeCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string EmployeeCode
		{
			get
			{
				return this._EmployeeCode;
			}
			set
			{
				if ((this._EmployeeCode != value))
				{
					this._EmployeeCode = value;
				}
			}
		}
		
		[Column(Storage="_HelpCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string HelpCode
		{
			get
			{
				return this._HelpCode;
			}
			set
			{
				if ((this._HelpCode != value))
				{
					this._HelpCode = value;
				}
			}
		}
		
		[Column(Storage="_Name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[Column(Storage="_Sex", DbType="VarChar(10)")]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this._Sex = value;
				}
			}
		}
		
		[Column(Storage="_Birthday", DbType="DateTime")]
		public System.Nullable<System.DateTime> Birthday
		{
			get
			{
				return this._Birthday;
			}
			set
			{
				if ((this._Birthday != value))
				{
					this._Birthday = value;
				}
			}
		}
		
		[Column(Storage="_Handset", DbType="VarChar(20)")]
		public string Handset
		{
			get
			{
				return this._Handset;
			}
			set
			{
				if ((this._Handset != value))
				{
					this._Handset = value;
				}
			}
		}
		
		[Column(Storage="_Tel", DbType="VarChar(20)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this._Tel = value;
				}
			}
		}
		
		[Column(Storage="_Addr", DbType="VarChar(100)")]
		public string Addr
		{
			get
			{
				return this._Addr;
			}
			set
			{
				if ((this._Addr != value))
				{
					this._Addr = value;
				}
			}
		}
		
		[Column(Storage="_IDCard", DbType="VarChar(22)")]
		public string IDCard
		{
			get
			{
				return this._IDCard;
			}
			set
			{
				if ((this._IDCard != value))
				{
					this._IDCard = value;
				}
			}
		}
		
		[Column(Storage="_EMail", DbType="VarChar(50)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this._EMail = value;
				}
			}
		}
		
		[Column(Storage="_Operator", DbType="VarChar(20)")]
		public string Operator
		{
			get
			{
				return this._Operator;
			}
			set
			{
				if ((this._Operator != value))
				{
					this._Operator = value;
				}
			}
		}
		
		[Column(Storage="_OperateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> OperateDate
		{
			get
			{
				return this._OperateDate;
			}
			set
			{
				if ((this._OperateDate != value))
				{
					this._OperateDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
