GO
DECLARE @NAME VARCHAR(50)
DECLARE @COUNT INT
SET @NAME = '矿外单位'
SET @COUNT = 0
SET @COUNT=(SELECT COUNT(*) FROM tb_MR_NUMBER)
IF @COUNT>5
BEGIN
	PRINT '该单位电话大于5部 '
END
ELSE
BEGIN
	PRINT '该单位电话小于5部'
END