//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCSharpSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingRoom
    {
        public MeetingRoom()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int Id { get; set; }
        public string RoomName { get; set; }
    
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
