#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompositeOrderby
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="db_TomeTwo")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClassesDataContext() : 
				base(global::CompositeOrderby.Properties.Settings.Default.db_TomeTwoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ProductInfo> ProductInfo
		{
			get
			{
				return this.GetTable<ProductInfo>();
			}
		}
	}
	
	[Table(Name="dbo.ProductInfo")]
	public partial class ProductInfo
	{
		
		private int _ID;
		
		private string _ProductCode;
		
		private string _HelpCode;
		
		private string _ShortName;
		
		private string _ProductName;
		
		private string _Specs;
		
		private string _ProductType;
		
		private string _Yieldly;
		
		private string _Unit;
		
		private string _WareHouse;
		
		private System.Nullable<int> _MaxStore;
		
		private System.Nullable<int> _MinStore;
		
		private System.Nullable<bool> _IsStop;
		
		private System.Nullable<double> _RetailPrice;
		
		private System.Nullable<double> _TradePrice;
		
		private System.Nullable<double> _MinimumPrice;
		
		private System.Nullable<double> _AdrisePrice;
		
		private System.Nullable<double> _CurMarketingPrice;
		
		private string _Operator;
		
		private System.Nullable<System.DateTime> _OperateDate;
		
		public ProductInfo()
		{
		}
		
		[Column(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[Column(Storage="_ProductCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this._ProductCode = value;
				}
			}
		}
		
		[Column(Storage="_HelpCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string HelpCode
		{
			get
			{
				return this._HelpCode;
			}
			set
			{
				if ((this._HelpCode != value))
				{
					this._HelpCode = value;
				}
			}
		}
		
		[Column(Storage="_ShortName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ShortName
		{
			get
			{
				return this._ShortName;
			}
			set
			{
				if ((this._ShortName != value))
				{
					this._ShortName = value;
				}
			}
		}
		
		[Column(Storage="_ProductName", DbType="VarChar(100)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[Column(Storage="_Specs", DbType="VarChar(50)")]
		public string Specs
		{
			get
			{
				return this._Specs;
			}
			set
			{
				if ((this._Specs != value))
				{
					this._Specs = value;
				}
			}
		}
		
		[Column(Storage="_ProductType", DbType="VarChar(20)")]
		public string ProductType
		{
			get
			{
				return this._ProductType;
			}
			set
			{
				if ((this._ProductType != value))
				{
					this._ProductType = value;
				}
			}
		}
		
		[Column(Storage="_Yieldly", DbType="VarChar(100)")]
		public string Yieldly
		{
			get
			{
				return this._Yieldly;
			}
			set
			{
				if ((this._Yieldly != value))
				{
					this._Yieldly = value;
				}
			}
		}
		
		[Column(Storage="_Unit", DbType="VarChar(10)")]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this._Unit = value;
				}
			}
		}
		
		[Column(Storage="_WareHouse", DbType="VarChar(20)")]
		public string WareHouse
		{
			get
			{
				return this._WareHouse;
			}
			set
			{
				if ((this._WareHouse != value))
				{
					this._WareHouse = value;
				}
			}
		}
		
		[Column(Storage="_MaxStore", DbType="Int")]
		public System.Nullable<int> MaxStore
		{
			get
			{
				return this._MaxStore;
			}
			set
			{
				if ((this._MaxStore != value))
				{
					this._MaxStore = value;
				}
			}
		}
		
		[Column(Storage="_MinStore", DbType="Int")]
		public System.Nullable<int> MinStore
		{
			get
			{
				return this._MinStore;
			}
			set
			{
				if ((this._MinStore != value))
				{
					this._MinStore = value;
				}
			}
		}
		
		[Column(Storage="_IsStop", DbType="Bit")]
		public System.Nullable<bool> IsStop
		{
			get
			{
				return this._IsStop;
			}
			set
			{
				if ((this._IsStop != value))
				{
					this._IsStop = value;
				}
			}
		}
		
		[Column(Storage="_RetailPrice", DbType="Float")]
		public System.Nullable<double> RetailPrice
		{
			get
			{
				return this._RetailPrice;
			}
			set
			{
				if ((this._RetailPrice != value))
				{
					this._RetailPrice = value;
				}
			}
		}
		
		[Column(Storage="_TradePrice", DbType="Float")]
		public System.Nullable<double> TradePrice
		{
			get
			{
				return this._TradePrice;
			}
			set
			{
				if ((this._TradePrice != value))
				{
					this._TradePrice = value;
				}
			}
		}
		
		[Column(Storage="_MinimumPrice", DbType="Float")]
		public System.Nullable<double> MinimumPrice
		{
			get
			{
				return this._MinimumPrice;
			}
			set
			{
				if ((this._MinimumPrice != value))
				{
					this._MinimumPrice = value;
				}
			}
		}
		
		[Column(Storage="_AdrisePrice", DbType="Float")]
		public System.Nullable<double> AdrisePrice
		{
			get
			{
				return this._AdrisePrice;
			}
			set
			{
				if ((this._AdrisePrice != value))
				{
					this._AdrisePrice = value;
				}
			}
		}
		
		[Column(Storage="_CurMarketingPrice", DbType="Float")]
		public System.Nullable<double> CurMarketingPrice
		{
			get
			{
				return this._CurMarketingPrice;
			}
			set
			{
				if ((this._CurMarketingPrice != value))
				{
					this._CurMarketingPrice = value;
				}
			}
		}
		
		[Column(Storage="_Operator", DbType="VarChar(20)")]
		public string Operator
		{
			get
			{
				return this._Operator;
			}
			set
			{
				if ((this._Operator != value))
				{
					this._Operator = value;
				}
			}
		}
		
		[Column(Storage="_OperateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> OperateDate
		{
			get
			{
				return this._OperateDate;
			}
			set
			{
				if ((this._OperateDate != value))
				{
					this._OperateDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
