<?xml version="1.0" encoding="utf-8"?>
<Database Name="db_TomeTwo" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MRWXK\WANGXIAOKE;Initial Catalog=db_TomeTwo;User ID=sa" SettingsObjectName="CompositeOrderby.Properties.Settings" SettingsPropertyName="db_TomeTwoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ProductInfo" Member="ProductInfo">
    <Type Name="ProductInfo">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="HelpCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ShortName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Specs" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProductType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Yieldly" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="WareHouse" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MaxStore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MinStore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsStop" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RetailPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TradePrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MinimumPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AdrisePrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CurMarketingPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Operator" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="OperateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>